# CI de Nível 04 - Pipeline GitLab CI

# Ordem de execução dos estágios
stages:
  - inspecao
  - unidade
  - e2e
  - deploy

# Âncora para reutilizar os passos de setup
.setup: &setup
  image: node:latest
  before_script:
    - npm install -g yarn
    - yarn

inspecao:
  <<: *setup
  stage: inspecao
  script:
    - yarn lint

unidade:
  <<: *setup
  stage: unidade
  needs: [inspecao]
  script:
    - yarn run test

e2e-tests:
  stage: e2e
  image: mcr.microsoft.com/playwright:v1.47.0-noble
  needs: [inspecao]
  before_script:
    - npm install -g yarn
    - yarn
  script:
    - yarn playwright install
    - yarn run e2e
  artifacts:
    when: always
    name: 'Relatório de Testes E2E'
    paths:
      - playwright-report/

deploy:
  <<: *setup
  stage: deploy
  needs: [unidade, e2e-tests]
  script:
    - echo 'Deploy sendo realizado...'
