name: 'N5 - Self-hosted Runner'

on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  self-hosted-tests:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Rodando testes unitários
        run: yarn run test